version: '3'
services:
  dev:
    build:
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    environment:
      DOCKER_HOST: tcp://localhost:2375
    volumes:
      - ..:/workspace:cached
      - nix:/nix
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - label:disable

volumes:
  nix:
